# Generated by Django 5.2 on 2025-05-21 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_enrollment_progress_enrollment_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='category',
            field=models.CharField(blank=True, choices=[('Programming', 'Programming'), ('Design', 'Design'), ('Marketing', 'Marketing'), ('Business', 'Business'), ('Other', 'Other')], default='Programming', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='level',
            field=models.CharField(blank=True, choices=[('Beginner', 'Beginner'), ('Intermediate', 'Intermediate'), ('Advanced', 'Advanced')], default='Beginner', max_length=50, null=True),
        ),
    ]
