# Generated by Django 5.2 on 2025-05-21 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_course_category_course_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='category',
            field=models.CharField(blank=True, choices=[('Programming', 'Programming'), ('Design', 'Design'), ('Marketing', 'Marketing'), ('Business', 'Business'), ('Data Science', 'Data Science')], default='Programming', max_length=50, null=True),
        ),
    ]
