# Generated by Django 5.2 on 2025-05-23 18:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0010_alter_course_instructor'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coursevideo',
            old_name='title',
            new_name='lesson_name',
        ),
        migrations.AlterUniqueTogether(
            name='enrollment',
            unique_together={('student', 'course')},
        ),
    ]
