# Generated by Django 5.2 on 2025-05-23 19:04

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0011_rename_title_coursevideo_lesson_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coursevideo',
            name='course',
        ),
        migrations.AddField(
            model_name='course',
            name='requirements',
            field=models.TextField(default='default text'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='course',
            name='videos',
            field=models.ManyToManyField(blank=True, related_name='courses', to='courses.coursevideo'),
        ),
        migrations.AddField(
            model_name='coursevideo',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='coursevideo',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='category',
            field=models.CharField(blank=True, choices=[('Programming', 'Programming'), ('Design', 'Design'), ('Marketing', 'Marketing'), ('Business', 'Business'), ('Data Science', 'Data Science')], default='Programming', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='courseType',
            field=models.CharField(choices=[('Free', 'Free'), ('Paid', 'Paid')], max_length=20),
        ),
        migrations.AlterField(
            model_name='course',
            name='level',
            field=models.CharField(blank=True, choices=[('Beginner', 'Beginner'), ('Intermediate', 'Intermediate'), ('Advanced', 'Advanced')], default='Beginner', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='slug',
            field=models.SlugField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='title',
            field=models.CharField(max_length=200),
        ),
    ]
