# Generated by Django 5.2 on 2025-05-23 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0012_remove_coursevideo_course_course_requirements_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='coursevideo',
            options={'ordering': ['order']},
        ),
        migrations.AddField(
            model_name='coursevideo',
            name='duration',
            field=models.PositiveIntegerField(default=0, help_text='Duration in minutes'),
        ),
        migrations.AddField(
            model_name='coursevideo',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
