# Generated by Django 5.2 on 2025-05-31 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0015_remove_course_videos_coursevideo_course'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursevideo',
            name='duration',
            field=models.PositiveIntegerField(default=0, help_text='Duration in seconds'),
        ),
        migrations.AlterUniqueTogether(
            name='coursevideo',
            unique_together={('course', 'order')},
        ),
    ]
